filmdesigners.at/Models/Enrollment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace filmdesigners.at.Models
{
    public class Enrollment
    {
        public string EnrollmentID { get; set; }
        public string ProjectID { get; set; }
        public string MemberID { get; set; }
        public string JobId { get; set; }

        public virtual Member Member { get; set; }
        public virtual Project Project { get; set; }
        public virtual Job Job { get; set; }
    }
}

filmdesigners.at/Controllers/EnrollmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using filmdesigners.at.Data;
using filmdesigners.at.Models;

namespace filmdesigners.at.Controllers
{
    public class EnrollmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EnrollmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Enrollments
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Enrollment.Include(e => e.Member).Include(e => e.Project);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Enrollments/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment
                .Include(e => e.Member)
                .Include(e => e.Project)
                .SingleOrDefaultAsync(m => m.EnrollmentID == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // GET: Enrollments/Create
        public IActionResult Create()
        {
            ViewData["MemberID"] = new SelectList(_context.Member, "MemberId", "Name");
            ViewData["ProjectID"] = new SelectList(_context.Project, "ProjectID", "Name");
            ViewData["JobID"] = new SelectList(_context.Job, "JobId", "Name");

            return View();
        }

        // POST: Enrollments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enrollment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MemberID"] = new SelectList(_context.Member, "MemberId", "MemberId", enrollment.MemberID);
            ViewData["ProjectID"] = new SelectList(_context.Project, "ProjectID", "ProjectID", enrollment.ProjectID);
            return View(enrollment);
        }

        // GET: Enrollments/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment.SingleOrDefaultAsync(m => m.EnrollmentID == id);
            if (enrollment == null)
            {
                return NotFound();
            }
            ViewData["MemberID"] = new SelectList(_context.Member, "MemberId", "MemberId", enrollment.MemberID);
            ViewData["ProjectID"] = new SelectList(_context.Project, "ProjectID", "ProjectID", enrollment.ProjectID);
            return View(enrollment);
        }

        // POST: Enrollments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("EnrollmentID,ProjectID,MemberID,Job")] Enrollment enrollment)
        {
            if (id != enrollment.EnrollmentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enrollment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnrollmentExists(enrollment.EnrollmentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MemberID"] = new SelectList(_context.Member, "MemberId", "MemberId", enrollment.MemberID);
            ViewData["ProjectID"] = new SelectList(_context.Project, "ProjectID", "ProjectID", enrollment.ProjectID);
            return View(enrollment);
        }

        // GET: Enrollments/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment
                .Include(e => e.Member)
                .Include(e => e.Project)
                .SingleOrDefaultAsync(m => m.EnrollmentID == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // POST: Enrollments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var enrollment = await _context.Enrollment.SingleOrDefaultAsync(m => m.EnrollmentID == id);
            _context.Enrollment.Remove(enrollment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EnrollmentExists(string id)
        {
            return _context.Enrollment.Any(e => e.EnrollmentID == id);
        }
    }
}

filmdesigners.at/Views/Enrollments/Create.cshtml
@model filmdesigners.at.Models.Enrollment

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Enrollment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Enrollments" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProjectID" class="control-label"></label>
                <select asp-for="ProjectID" class ="form-control" asp-items="ViewBag.ProjectID"></select>
            </div>
            <div class="form-group">
                <label asp-for="MemberID" class="control-label"></label>
                <select asp-for="MemberID" class ="form-control" asp-items="ViewBag.MemberID"></select>
            </div>
            <div class="form-group">
                <label asp-for="JobId" class="control-label"></label>
                <select asp-for="JobId" class="form-control" asp-items="ViewBag.JobID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

filmdesigners.at/Views/Enrollments/Delete.cshtml
@model filmdesigners.at.Models.Enrollment

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Job)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Job)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Member.MemberId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Project.ProjectID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EnrollmentID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

filmdesigners.at/Views/Enrollments/Details.cshtml
@model filmdesigners.at.Models.Enrollment

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Job)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Job)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Member.MemberId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Project.ProjectID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EnrollmentID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

filmdesigners.at/Views/Enrollments/Edit.cshtml
@model filmdesigners.at.Models.Enrollment

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Enrollment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EnrollmentID" />
            <div class="form-group">
                <label asp-for="ProjectID" class="control-label"></label>
                <select asp-for="ProjectID" class="form-control" asp-items="ViewBag.ProjectID"></select>
                <span asp-validation-for="ProjectID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberID" class="control-label"></label>
                <select asp-for="MemberID" class="form-control" asp-items="ViewBag.MemberID"></select>
                <span asp-validation-for="MemberID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Job" class="control-label"></label>
                <input asp-for="Job" class="form-control" />
                <span asp-validation-for="Job" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

filmdesigners.at/Views/Enrollments/Index.cshtml
@model IEnumerable<filmdesigners.at.Models.Enrollment>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Job)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Member)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Job)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Member.MemberId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.ProjectID)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.EnrollmentID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.EnrollmentID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.EnrollmentID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>