filmdesigners.at/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using filmdesigners.at.Data;
using filmdesigners.at.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using filmdesigners.at.Authorization;
using filmdesigners.at.Models.MemberViewModels;
using filmdesigners.at.Services;
using System.IO;

namespace filmdesigners.at.Controllers
{
    public class MembersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAuthorizationService _authorizationService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;

        public MembersController(ApplicationDbContext context, IAuthorizationService authorizationService, UserManager<ApplicationUser> userManager, IEmailSender emailSender)
        {
            _context = context;
            _authorizationService = authorizationService;
            _userManager = userManager;
            _emailSender = emailSender;
        }

        // GET: Members/5 (Department
        [AllowAnonymous]
        public async Task<IActionResult> Index(string job)
        {
            
            var Jobs = _context.Job.OrderBy(j => j.Priority).ToArray();
            ViewData["Jobs"] = Jobs;
            if (job != null)
            {
                ViewData["Job"] = _context.Job.Where(j => j.JobId == job).First();
                return View(await _context.Member.Where(m => m.JobId == job).OrderBy(m => m.Priority).ToListAsync());
            }
            else
            {
                return View(await _context.Member.OrderBy(m => m.Priority).ToListAsync());
            }
        }

        // GET: Members/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .Include(m => m.Enrollments)
                .ThenInclude(e => e.Project)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }
            var Jobs = _context.Job.OrderBy(j => j.Priority).ToArray();
            ViewData["Jobs"] = Jobs;
            List<Enrollment> Enrollments = _context.Enrollment.Where(e => e.Member == member).ToList();
            foreach(Enrollment e in Enrollments)
            {
                e.Project = await _context.Project.Where(p => p.ProjectID == e.ProjectID).FirstOrDefaultAsync();
            }
            var groupedEnrollments = Enrollments.GroupBy(e => e.Project.Date.Year).Select(grp => grp.ToList()).ToList();
            ViewData["Enrollments"] = groupedEnrollments;
            ViewData["MemberID"] = new SelectList(_context.Member, "MemberId", "Name");
            ViewData["ProjectID"] = new SelectList(_context.Project, "ProjectID", "Name");
            ViewData["JobID"] = new SelectList(_context.Job, "JobId", "Name");
            return View(member);
        }

        // GET: Members/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Member member)
        {
            if (!ModelState.IsValid)
            {
                return View(member);
            }

            member.OwnerID = _userManager.GetUserId(User);

            var isAuthorized = await _authorizationService.AuthorizeAsync(User, member, MemberOperations.Create);

            if(!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }

            _context.Add(member);

            await _context.SaveChangesAsync();

            await _emailSender.SendEmailAsync("m@steinbach.io", "New Member",
                   $"Please approve or reject the new Member " + member.Name + ".");

            return RedirectToAction("Index");
        }

        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member.SingleOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            var isAuthorized = await _authorizationService.AuthorizeAsync(User, member, MemberOperations.Update);

            if(!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }

            ViewData["JobID"] = new SelectList(_context.Job, "JobId", "Name");
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, MemberEditViewModel editModel)
        {
            if(!ModelState.IsValid)
            {
                return View(editModel);
            }

            // Get Member from DB to get OwnerID
            var member = await _context.Member.SingleOrDefaultAsync(m => m.MemberId == id);
            if(member == null)
            {
                return NotFound();
            }

            var isAuthorized = await _authorizationService.AuthorizeAsync(User, member, MemberOperations.Update);

            if(!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }

            member = viewModel2Model(member, editModel);

            if(member.Status == Models.MemberStatus.Approved)
            {
                // If the Model was updated after the approval,
                // and the user cannpt approve, set the status back to submitted.
                var canApprove = await _authorizationService.AuthorizeAsync(User, member, MemberOperations.Approve);

                if(!canApprove.Succeeded)
                {
                    member.Status = Models.MemberStatus.Submitted;
                }
            }
            // create file with picture
            if (editModel.Picture != null)
            {
                Guid PictureID = Guid.NewGuid();
                string fileType = member.Picture.Split('/')[1].Split(';')[0];
                string PicturesPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", $"{PictureID}.{fileType}");

                var bytes = Convert.FromBase64String(member.Picture.Split(',')[1]);
                if (bytes.Length > 0)
                {
                    using (var stream = new FileStream(PicturesPath, FileMode.Create))
                    {
                        stream.Write(bytes, 0, bytes.Length);
                        stream.Flush();
                    }
                }
                member.Picture = $"{PictureID.ToString()}.{fileType}";
            }
            _context.Update(member);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        // GET: Members/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .SingleOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            var isAuthorized = await _authorizationService.AuthorizeAsync(User, member, MemberOperations.Delete);

            if(!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }

            return View(member);
        }

        // GET: Members/Upgrade/5
        public async Task<IActionResult> Upgrade(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .SingleOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            var isAuthorized = await _authorizationService.AuthorizeAsync(User, member, MemberOperations.UpgradeMember);

            if (!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }

            if(member.Priority > 0)
            {
                member.Priority--;
                _context.Update(member);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        // GET: Members/Downgrade/5
        public async Task<IActionResult> Downgrade(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .SingleOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            var isAuthorized = await _authorizationService.AuthorizeAsync(User, member, MemberOperations.DowngradeMember);

            if (!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }
            member.Priority++;
            _context.Update(member);
            await _context.SaveChangesAsync();

filmdesigners.at/Views/Members/Create.cshtml
@model filmdesigners.at.Models.Member

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OwnerID" class="control-label"></label>
                <input asp-for="OwnerID" class="form-control" />
                <span asp-validation-for="OwnerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Male" /> @Html.DisplayNameFor(model => model.Male)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZIP" class="control-label"></label>
                <input asp-for="ZIP" class="form-control" />
                <span asp-validation-for="ZIP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Website" class="control-label"></label>
                <input asp-for="Website" class="form-control" />
                <span asp-validation-for="Website" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fax" class="control-label"></label>
                <input asp-for="Fax" class="form-control" />
                <span asp-validation-for="Fax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OtherContact" class="control-label"></label>
                <input asp-for="OtherContact" class="form-control" />
                <span asp-validation-for="OtherContact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deathday" class="control-label"></label>
                <input asp-for="Deathday" class="form-control" />
                <span asp-validation-for="Deathday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Languages" class="control-label"></label>
                <input asp-for="Languages" class="form-control" />
                <span asp-validation-for="Languages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InternationalExperiences" class="control-label"></label>
                <input asp-for="InternationalExperiences" class="form-control" />
                <span asp-validation-for="InternationalExperiences" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Education" class="control-label"></label>
                <input asp-for="Education" class="form-control" />
                <span asp-validation-for="Education" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Activities" class="control-label"></label>
                <input asp-for="Activities" class="form-control" />
                <span asp-validation-for="Activities" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Galleries" class="control-label"></label>
                <input asp-for="Galleries" class="form-control" />
                <span asp-validation-for="Galleries" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Awards" class="control-label"></label>
                <input asp-for="Awards" class="form-control" />
                <span asp-validation-for="Awards" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EMail" class="control-label"></label>
                <input asp-for="EMail" class="form-control" />
                <span asp-validation-for="EMail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Locked" /> @Html.DisplayNameFor(model => model.Locked)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Resigned" /> @Html.DisplayNameFor(model => model.Resigned)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Paused" /> @Html.DisplayNameFor(model => model.Paused)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="LastUpdate" class="control-label"></label>
                <input asp-for="LastUpdate" class="form-control" />
                <span asp-validation-for="LastUpdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

filmdesigners.at/Views/Members/Delete.cshtml
@model filmdesigners.at.Models.Member

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OwnerID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OwnerID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Male)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Male)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ZIP)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ZIP)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OtherContact)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OtherContact)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Deathday)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Deathday)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Languages)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Languages)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.InternationalExperiences)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InternationalExperiences)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Education)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Education)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Activities)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Activities)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Galleries)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Galleries)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Awards)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Awards)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EMail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EMail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Locked)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Locked)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Resigned)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Resigned)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Paused)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Paused)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastUpdate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastUpdate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MemberId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

filmdesigners.at/Views/Members/Details.cshtml
@model filmdesigners.at.Models.Member
@{
    ViewData["Title"] = "Details";
    bool firstProjectCard = true;
}

@await Html.PartialAsync("_DepartmentPartial")
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <div class="d-flex justify-content-between flex-wrap align-items-center pb-2 mb-3 border-bottom">
    <h2>Details</h2>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <img src="/images/@Html.DisplayFor(model => model.Picture)" />
            </div>
            <div class="col-md-8">
                <h3>
                    @Html.DisplayFor(model => model.Name)
                </h3>
                <a href="mailto:@Html.DisplayFor(model => model.EMail)">
                    @Html.DisplayFor(model => model.EMail)
                </a>
                <br />
                <a href="tel:@Html.DisplayFor(model => model.Mobile)">@Html.DisplayFor(model => model.Mobile)</a>
                <br />
                <a href="tel:@Html.DisplayFor(model => model.Phone)">@Html.DisplayFor(model => model.Phone)</a>
                <br />
                <span>
                    @Html.DisplayFor(model => model.Street)
                </span>
                <br />
                <span>
                    @Html.DisplayFor(model => model.ZIP) @Html.DisplayFor(model => model.City)
                </span>
                <br />
                <span>
                    @Html.DisplayFor(model => model.Country)
                </span>
            </div>
        </div>
        <div class="accordion" id="projectsAccordion">
            @foreach (var year in (List<List<Enrollment>>)ViewData["Enrollments"])
            {
                <div class="card">
                    <div class="card-header project-toggle" id="@year.First().Project.Date.Year-h">
                        <h5 class="mb-0">
                            <a class="btn" data-toggle="collapse" data-target="#@year.First().Project.Date.Year" aria-expanded="true" aria-controls="@year.First().Project.Date.Year">
                                @year.First().Project.Date.Year
                            </a>
                        </h5>
                    </div>
                    @if(firstProjectCard)
                    {
                            <div id="@year.First().Project.Date.Year" class="collapse show" aria-labelledby="@year.First().Project.Date.Year-h" data-parent="#projectsAccordion">
                            <div class="card-body">
                                @foreach(var enrollment in year)
                                {
                                    <div class="container-fluid">
                                        <div class="row">
                                            <div class="col-6">
                                                @enrollment.Project.Name
                                            </div>
                                            <div class="col-6">
                                                @enrollment.Job.Name
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                        firstProjectCard = false;
                    }
                    else
                    {

                            <div id="@year.First().Project.Date.Year" class="collapse" aria-labelledby="@year.First().Project.Date.Year" data-parent="#projectsAccordion">
                            <div class="card-body">
                                @foreach(var enrollment in year)
                                {
                                    <div class="container-fluid">
                                        <div class="row">
                                            <div class="col-6">
                                                @enrollment.Project.Name
                                            </div>
                                            <div class="col-6">
                                                @enrollment.Job.Name
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    }
               </div>
            }
        </div>
    </div>
</div>
@if (AuthorizationService.AuthorizeAsync(User, new Enrollment(), EnrollmentOperations.Create).Result.Succeeded)
{
<div class=container-fluid>
    @Html.Partial("~/Views/Enrollments/Create.cshtml", new Enrollment())
</div>
}
@if (Model.Status != MemberStatus.Approved)
{
    @if (AuthorizationService.AuthorizeAsync(User, Model, MemberOperations.Approve).Result.Succeeded)
    {
        <form asp-action="SetStatus" asp-controller="Members" style="display:inline;">
            <input type="hidden" name="id" value="@Model.MemberId" />
            <input type="hidden" name="status" value="@MemberStatus.Approved" />
            <button type="submit" class="btn btn-xs btn-success">Approve</button>
        </form>
    }
}
@if (Model.Status != MemberStatus.Rejected)
{
    @if (AuthorizationService.AuthorizeAsync(User, Model, MemberOperations.Reject).Result.Succeeded)
    {
        <form asp-action="SetStatus" asp-controller="Members" style="display:inline;">
            <input type="hidden" name="id" value="@Model.MemberId" />
            <input type="hidden" name="status" value="@MemberStatus.Rejected" />
            <button type="submit" class="btn btn-xs btn-danger">Reject</button>
        </form>
    }
}
<div>
    <a asp-action="Edit" asp-route-id="@Model.MemberId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
    </main>

filmdesigners.at/Views/Members/_SidePartial.cshtml
<nav class="col-md-2 d-none d-md-block bg-dark sidebar navbar-dark">
    <div class="sidebar-sticky navbar-dark">
        <ul class="nav flex-column navbar-nav">
            @foreach(var Job in ViewData["Jobs"] as IEnumerable<Job>)
            {
                if(!Job.isPartner)
                {
                    <li class="nav-item">
                        <a class="nav-link" href="#">@Job.Name</a>
                    </li>
                }
            }
        </ul>
        <div id="partner-accordion" role="tablist" aria-multiselectable="true" class="navbar-nav">
            <a data-toggle="collapse" data-parent="#accordion" href="#partnerCollapse" aria-expanded="true" aria-controls="partnerCollapse" class="nav-link">
                Partner
            </a>
            <div id="partnerCollapse" class="collapse" role="tabpanel" aria-labelledby="partnerHeading">
                <ul class="nav nav-pills flex-column partner-nav">
                @foreach(var Job in ViewData["Jobs"] as IEnumerable<Job>)
                {
                    if(Job.isPartner)
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="#">@Job.Name</a>
                        </li>
                    }
                }
                </ul>
            </div>
        </div>
    </div>
</nav>